"""initial schema

Revision ID: 14713c5cbb11
Revises: 
Create Date: 2026-04-24 03:36:15.054894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14713c5cbb11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('lifecycle_state', sa.Enum('open', 'closed', 'archived', name='lead_lifecycle_state', native_enum=False), nullable=False),
    sa.Column('current_score_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'lead_id')
    )
    op.create_table('model_versions',
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('model_scope', sa.Enum('global', 'tenant', 'segment', name='model_scope', native_enum=False), nullable=False),
    sa.Column('scope_key', sa.String(), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('candidate', 'approved', 'active', 'rolled_back', 'retired', name='model_status', native_enum=False), nullable=False),
    sa.Column('training_window', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('artifact_uri', sa.String(), nullable=False),
    sa.CheckConstraint("(model_scope = 'global' AND scope_key IS NULL) OR (model_scope IN ('tenant', 'segment') AND scope_key IS NOT NULL)", name='ck_model_versions_scope_key'),
    sa.PrimaryKeyConstraint('model_version')
    )
    op.create_index('ix_model_versions_scope_scope_key', 'model_versions', ['model_scope', 'scope_key'], unique=False)
    bind = op.get_bind()
    if bind is not None and bind.dialect.name == "postgresql":
        op.create_index(
            "uq_model_versions_active_per_scope",
            "model_versions",
            ["model_scope", "scope_key"],
            unique=True,
            postgresql_where=sa.text("status = 'active'"),
        )
    op.create_table('tenant_scoring_policies',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('scoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('threshold_cold_max', sa.Float(), nullable=False),
    sa.Column('threshold_hot_min', sa.Float(), nullable=False),
    sa.Column('override_enabled', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.CheckConstraint('threshold_cold_max < threshold_hot_min', name='ck_tenant_scoring_policy_threshold_order'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('lead_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'lead_id'], ['leads.tenant_id', 'leads.lead_id'], name='fk_lead_events_lead'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_lead_events_tenant_lead_event_ts', 'lead_events', ['tenant_id', 'lead_id', 'event_ts'], unique=False)
    op.create_table('lead_feature_snapshots',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('feature_cutoff_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_vector', sa.JSON(), nullable=False),
    sa.Column('feature_schema_version', sa.String(), nullable=False),
    sa.Column('is_leakage_validated', sa.Boolean(), nullable=False),
    sa.Column('feature_snapshot_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'lead_id'], ['leads.tenant_id', 'leads.lead_id'], name='fk_feature_snapshots_lead'),
    sa.PrimaryKeyConstraint('tenant_id', 'lead_id', 'feature_cutoff_ts')
    )
    op.create_index(
        'ix_feature_snapshots_tenant_lead_cutoff_desc',
        'lead_feature_snapshots',
        ['tenant_id', 'lead_id', sa.text('feature_cutoff_ts DESC')],
        unique=False,
    )
    op.create_table('score_explanations',
    sa.Column('explanation_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('score_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('top_signals', sa.JSON(), nullable=False),
    sa.Column('recommended_action', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'lead_id'], ['leads.tenant_id', 'leads.lead_id'], name='fk_score_explanations_lead'),
    sa.PrimaryKeyConstraint('explanation_id'),
    sa.UniqueConstraint('tenant_id', 'lead_id', 'score_ts', name='uq_score_explanations_tenant_lead_score_ts')
    )
    op.create_table('lead_scores',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('score_probability', sa.Float(), nullable=False),
    sa.Column('score_category', sa.Enum('cold', 'warm', 'hot', name='score_category', native_enum=False), nullable=False),
    sa.Column('threshold_policy_version', sa.String(), nullable=False),
    sa.Column('score_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('feature_cutoff_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_snapshot_ref', sa.String(), nullable=True),
    sa.Column('is_cold_start', sa.Boolean(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('staleness_seconds', sa.Integer(), nullable=False),
    sa.CheckConstraint('score_probability >= 0.0 AND score_probability <= 1.0', name='ck_lead_scores_probability_range'),
    sa.ForeignKeyConstraint(['model_version'], ['model_versions.model_version'], name='fk_lead_scores_model_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'lead_id', 'feature_cutoff_ts'], ['lead_feature_snapshots.tenant_id', 'lead_feature_snapshots.lead_id', 'lead_feature_snapshots.feature_cutoff_ts'], name='fk_lead_scores_feature_snapshot'),
    sa.ForeignKeyConstraint(['tenant_id', 'lead_id'], ['leads.tenant_id', 'leads.lead_id'], name='fk_lead_scores_lead'),
    sa.PrimaryKeyConstraint('tenant_id', 'lead_id', 'feature_cutoff_ts', 'model_version')
    )
    op.create_index('ix_lead_scores_tenant_lead', 'lead_scores', ['tenant_id', 'lead_id'], unique=False)
    op.create_index(
        'ix_lead_scores_tenant_lead_score_ts_desc',
        'lead_scores',
        ['tenant_id', 'lead_id', sa.text('score_ts DESC')],
        unique=False,
    )
    op.create_index(
        'ix_lead_scores_tenant_score_ts_desc',
        'lead_scores',
        ['tenant_id', sa.text('score_ts DESC')],
        unique=False,
    )
    op.create_index('ix_lead_scores_tenant_stale_score_ts', 'lead_scores', ['tenant_id', 'is_stale', 'score_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lead_scores_tenant_stale_score_ts', table_name='lead_scores')
    op.drop_index('ix_lead_scores_tenant_score_ts_desc', table_name='lead_scores')
    op.drop_index('ix_lead_scores_tenant_lead_score_ts_desc', table_name='lead_scores')
    op.drop_index('ix_lead_scores_tenant_lead', table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_table('score_explanations')
    op.drop_index('ix_feature_snapshots_tenant_lead_cutoff_desc', table_name='lead_feature_snapshots')
    op.drop_table('lead_feature_snapshots')
    op.drop_index('ix_lead_events_tenant_lead_event_ts', table_name='lead_events')
    op.drop_table('lead_events')
    op.drop_table('tenant_scoring_policies')
    bind = op.get_bind()
    if bind is not None and bind.dialect.name == "postgresql":
        op.drop_index(
            "uq_model_versions_active_per_scope",
            table_name="model_versions",
            postgresql_where=sa.text("status = 'active'"),
        )
    op.drop_index('ix_model_versions_scope_scope_key', table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_table('leads')
    # ### end Alembic commands ###
